name: pre-commit-bump-bot
description: GHA to bump pre-commit versions in a repository and create a pull request with the changes.
author: Ramon Vermeulen

branding:
  icon: arrow-up-right
  color: yellow

inputs:
  command:
    description: Command to run, can be either `update` or `check`.
    default: update
    required: false
  allow:
    description: Specific semantic versioning range to allow updates for (major, minor, patch), uses major if not specified.
    default: major
    required: false
  verbose:
    description: Whether to run in verbose mode.
    default: "false"
    required: false
  config:
    description: Path to the pre-commit configuration file, uses `.pre-commit-config.yaml` if not specified.
    default: .pre-commit-config.yaml
    required: false
  no-summary:
    description: Whether to skip the summary output.
    required: false
    default: "false"
  dry-run:
    description: Whether to perform a dry run without making changes.
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Run pre-commit-bump
      uses: ramonvermeulen/pre-commit-bump-gha@v1
      with:
        command: ${{ inputs.command }}
        allow: ${{ inputs.allow }}
        verbose: ${{ inputs.verbose }}
        config: ${{ inputs.config }}
        no-summary: ${{ inputs.no-summary }}
        dry-run: ${{ inputs.dry-run }}

    - name: Check for summary file
      id: check_summary
      run: |
        if [[ -f "summary.md" ]]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Create Pull Request with bumped pre-commit versions
      uses: peter-evans/create-pull-request@v7
      if: steps.check_summary.outputs.exists == 'true'
      with:
        commit-message: "chore(pre-commit): bump pre-commit versions"
        title: "chore(pre-commit): bump pre-commit versions"
        add-paths: |
          ${{ inputs.config }}
        branch: chore/pre-commit-bump
        body-path: summary.md
