- id: pre-commit-bump
  name: pre-commit-bump
  description: Bump pre-commit hook versions in your repository.
  language: docker_image
  entry: ghcr.io/ramonvermeulen/pre-commit-bump:v1 pre-commit-bump update
  pass_filenames: false
  verbose: true
  args:
    - --no-summary
    - --verbose
  always_run: true
