name: CD

on:
  push:
    tags:
      - "**"

env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "ramonvermeulen/pre-commit-bump"

jobs:
  build:
    name: CD
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Get major version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Log in to the Container registry
        if: ${{ steps.get_version.outputs.is-semver == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        if: ${{ steps.get_version.outputs.is-semver == 'true' }}
        with:
          push: true
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v${{ steps.get_version.outputs.major }}
