name: CI
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.25.0

      - name: Install Go tools for pre-commit
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
          go install golang.org/x/lint/golint@latest

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.11"
          enable-cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4

      - name: Install pre-commit
        run: |
          uv tool install pre-commit

      - name: Restore pre-commit hooks cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cache/uv
          key: pre-commit-uv|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: pre-commit
        run: SKIP=golangci-lint uv run pre-commit run --show-diff-on-failure --color=always --all-files
