name: CI
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.11"
          enable-cache: true

      - name: Install pre-commit
        run: |
          uv tool install pre-commit

      - name: Restore pre-commit hooks cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cache/uv
          key: pre-commit-uv|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: pre-commit
        run: uv run pre-commit run --show-diff-on-failure --color=always --all-files
